version: "3.7"

services:
  mongo:
    image: bitnami/mongodb:7.0.4
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicaSet
      MONGODB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: pass
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: pass
      MONGODB_DATABASE: db